name: Deploy to Azure VM

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Run remote deploy script via SSH
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.VM_HOST }}         # IP p√∫blico
        username: ${{ secrets.VM_USER }}
        password: ${{ secrets.VM_PASSWORD }} # ou use chave privada com private_key
        port: 22
        script: |
          cd /home/${{ secrets.VM_USER }}/deploy
          git pull || true
          bash install_k3s_with_docker.sh || true
          kubectl apply -f nginx-pod.yaml
          kubectl apply -f nginx-service-nodeport.yaml